ROLE_WEB_KNOWLEDGE_DOCS = {
    "Java后端工程师": [
        {
            "title": "Java并发与线程基础",
            "tags": ["java", "并发", "线程", "juc"],
            "source_name": "Oracle Java Tutorials",
            "source_url": "https://docs.oracle.com/javase/tutorial/essential/concurrency/index.html",
            "content": "Java 官方并发教程强调线程是并发程序的基本执行单元，工程面试通常会继续追问线程创建、线程池、同步、活跃性问题以及为什么优先使用高层并发工具。",
        },
        {
            "title": "Spring 事务管理",
            "tags": ["spring", "transaction", "@Transactional", "aop"],
            "source_name": "Spring Framework Reference",
            "source_url": "https://docs.spring.io/spring-framework/reference/data-access/transaction.html",
            "content": "Spring 事务管理提供一致的事务抽象、声明式事务和编程式事务支持。面试时常从 @Transactional 原理、传播行为、回滚规则和 AOP 代理切入，再追问失效场景。",
        },
        {
            "title": "MySQL 索引优化",
            "tags": ["mysql", "index", "optimizer", "sql优化"],
            "source_name": "MySQL 8.4 Reference Manual",
            "source_url": "https://dev.mysql.com/doc/en/optimization-indexes.html",
            "content": "MySQL 官方文档强调索引能加速 WHERE 过滤，但过多索引会占空间并增加写入成本。知识库应覆盖联合索引、最左前缀、回表、索引失效和写放大取舍。",
        },
        {
            "title": "Redis 数据结构与持久化",
            "tags": ["redis", "data types", "persistence", "cache"],
            "source_name": "Redis Docs",
            "source_url": "https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/",
            "content": "Redis 官方文档覆盖常见数据类型和 RDB、AOF 等持久化策略。岗位知识库应把缓存场景、持久化权衡、热点 key 和一致性问题作为核心考点。",
        },
    ],
    "Web前端工程师": [
        {
            "title": "React 组件纯函数与渲染约束",
            "tags": ["react", "pure components", "render"],
            "source_name": "React Docs",
            "source_url": "https://react.dev/learn/keeping-components-pure",
            "content": "React 官方强调组件应像纯函数一样，同样输入产生同样 JSX，且不要在 render 阶段修改外部状态。知识库应覆盖 render purity、副作用放置位置和状态更新时机。",
        },
        {
            "title": "JavaScript 事件循环与微任务",
            "tags": ["javascript", "event loop", "task", "microtask"],
            "source_name": "MDN Web Docs",
            "source_url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop",
            "content": "MDN 对 JavaScript 执行模型的说明覆盖调用栈、任务队列、微任务队列与 run-to-completion。前端知识库应重点沉淀事件循环、Promise 回调和渲染时机。",
        },
        {
            "title": "TypeScript 类型收窄与类型系统",
            "tags": ["typescript", "narrowing", "generics", "types"],
            "source_name": "TypeScript Handbook",
            "source_url": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
            "content": "TypeScript 官方手册把 narrowing 作为核心能力之一，强调通过控制流分析细化类型。知识库应覆盖联合类型、类型守卫、泛型和工程可维护性。",
        },
    ],
    "C++开发工程师": [
        {
            "title": "C++ 指针与所有权",
            "tags": ["c++", "pointers", "ownership", "memory"],
            "source_name": "Microsoft Learn",
            "source_url": "https://learn.microsoft.com/en-us/cpp/cpp/pointers-cpp?view=msvc-170",
            "content": "Microsoft C++ 文档指出原始指针是常见错误来源，现代 C++ 更推荐智能指针、迭代器和 lambda。知识库应覆盖所有权语义、悬垂指针和生命周期。",
        },
        {
            "title": "C++ RAII 与资源管理",
            "tags": ["c++", "raii", "resource management", "exception safety"],
            "source_name": "Microsoft Learn",
            "source_url": "https://learn.microsoft.com/en-us/cpp/cpp/object-lifetime-and-resource-management-modern-cpp?view=msvc-170",
            "content": "官方文档把 RAII 视为现代 C++ 资源管理核心，强调资源应由对象在初始化时获取、在析构时释放。知识库应沉淀 RAII、异常安全和资源泄漏防治。",
        },
        {
            "title": "C++ 智能指针",
            "tags": ["c++", "smart pointer", "unique_ptr", "shared_ptr", "weak_ptr"],
            "source_name": "Microsoft Learn",
            "source_url": "https://learn.microsoft.com/en-us/%20cpp/cpp/smart-pointers-modern-cpp?view=msvc-170",
            "content": "现代 C++ 智能指针文档强调 unique_ptr、shared_ptr、weak_ptr 用于避免泄漏并提升异常安全。知识库应覆盖引用计数、循环引用和所有权转移。",
        },
    ],
    "测试工程师": [
        {
            "title": "Playwright 自动等待与可操作性检查",
            "tags": ["testing", "playwright", "ui automation", "actionability"],
            "source_name": "Playwright Docs",
            "source_url": "https://playwright.dev/docs/actionability",
            "content": "Playwright 官方文档说明点击等动作前会自动执行可见、稳定、可接收事件、已启用等检查。知识库应覆盖自动等待机制、误报来源和 UI 自动化稳定性设计。",
        },
        {
            "title": "JUnit 5 测试结构与断言",
            "tags": ["testing", "junit5", "assertions", "parameterized tests"],
            "source_name": "JUnit 5 User Guide",
            "source_url": "https://docs.junit.org/5.11.3/user-guide/index.html",
            "content": "JUnit 5 用户指南覆盖注解模型、断言、异常断言、条件执行和参数化测试。知识库应把测试分层、断言设计和异常验证列为高频考点。",
        },
        {
            "title": "API 测试与断言设计",
            "tags": ["testing", "api testing", "assertions", "postman"],
            "source_name": "Postman Learning Center",
            "source_url": "https://learning.postman.com/docs/tests-and-scripts/write-scripts/test-scripts/",
            "content": "Postman 官方文档强调脚本化断言、响应校验和自动化执行。测试岗位知识库应覆盖接口断言、鉴权、幂等、数据清理和自动化集成。",
        },
    ],
    "Python算法工程师": [
        {
            "title": "Python asyncio 并发模型",
            "tags": ["python", "asyncio", "concurrency", "io-bound"],
            "source_name": "Python Docs",
            "source_url": "https://docs.python.org/3/library/asyncio.html",
            "content": "Python 官方文档把 asyncio 定义为基于 async/await 的并发库，适合 IO-bound 和高层结构化网络代码。知识库可用它补充工程落地部分。",
        },
        {
            "title": "PyTorch 自动求导",
            "tags": ["pytorch", "autograd", "backpropagation", "training"],
            "source_name": "PyTorch Docs",
            "source_url": "https://docs.pytorch.org/docs/stable/notes/autograd.html",
            "content": "PyTorch 对 autograd 的说明强调其通过记录前向操作图来实现反向自动微分。算法知识库应覆盖计算图、梯度传播、梯度清零和 in-place 操作风险。",
        },
        {
            "title": "模型评估与交叉验证",
            "tags": ["scikit-learn", "cross validation", "evaluation", "overfitting"],
            "source_name": "scikit-learn User Guide",
            "source_url": "https://scikit-learn.org/stable/modules/cross_validation",
            "content": "scikit-learn 官方用户指南强调不能在同一数据上训练和评估，否则会过拟合。知识库应覆盖 train/test split、交叉验证、数据泄漏和指标选择。",
        },
    ],
}
