from typing import Optional

from pydantic import BaseModel, Field

from app.schemas.evaluation import EvidencePack

class CodeExecutionEvidence(BaseModel):
    language: str = Field(default="", max_length=32)
    status: str = Field(default="", max_length=128)
    passed: Optional[bool] = None
    time: Optional[str] = Field(default=None, max_length=64)
    memory: Optional[int] = None
    stdout: str = Field(default="", max_length=2000)
    stderr: str = Field(default="", max_length=2000)
    compile_output: str = Field(default="", max_length=2000)
    message: str = Field(default="", max_length=1000)


class LLMRequest(BaseModel):
    user_message: str = Field(description="Chat message")
    chat_id: str = Field(description="Chat ID")
    skill_name: Optional[str] = Field(default=None, description="Registered skill name to run")
    interview_role: Optional[str] = Field(default=None, description="Interview role")
    interview_level: Optional[str] = Field(default=None, description="Interview level")
    interview_type: Optional[str] = Field(default=None, description="Interview type")
    target_company: Optional[str] = Field(default=None, description="Target company")
    jd_content: Optional[str] = Field(default=None, description="Job description content")
    resume_content: Optional[str] = Field(default=None, description="Resume content or summary")
    code_execution: Optional[CodeExecutionEvidence] = Field(default=None, description="Latest Judge0 result for a coding interview answer")
    knowledge_context: Optional[str] = Field(default=None, description="User-uploaded technical evidence context")
    evidence_pack: Optional[EvidencePack] = Field(default=None, description="Structured career evidence generated by the backend")
    knowledge_context_cache_hit: bool = Field(default=False, description="Whether the bounded career evidence pack came from Redis")
    knowledge_fact_id: Optional[int] = Field(default=None, description="Optional career fact used to scope technical evidence retrieval")


class CodeRunRequest(BaseModel):
    language: str = Field(description="Programming language key, e.g. python/cpp/java")
    source_code: str = Field(description="Source code to run")
    stdin: str = Field(default="", description="Custom standard input")
    expected_output: Optional[str] = Field(default=None, description="Expected output for simple pass/fail matching")


class CodeRunResponse(BaseModel):
    status: str = Field(description="Judge status description")
    stdout: str = Field(default="", description="Program stdout")
    stderr: str = Field(default="", description="Program stderr")
    compile_output: str = Field(default="", description="Compiler output")
    message: str = Field(default="", description="Judge message")
    time: Optional[str] = Field(default=None, description="Execution time returned by Judge0")
    memory: Optional[int] = Field(default=None, description="Memory usage returned by Judge0")
    token: Optional[str] = Field(default=None, description="Judge0 submission token")
    passed: Optional[bool] = Field(default=None, description="Whether stdout matches expected_output")


class CodeRunJobResponse(BaseModel):
    job_id: str
    status: str
    result: Optional[CodeRunResponse] = None
    error: Optional[str] = None
