JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=false
ENABLE_COMMAND_LINE_ARGUMENTS=false
ENABLE_SUBMISSION_DELETE=false
ALLOW_ORIGIN=
REDIS_HOST=redis
REDIS_PASSWORD=judge0_7ed4e251b9c84d4b8f3a05d74a8ecf2d
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_d1b8c43ce91a4f02a7d54e6b8f3c09da
COUNT=1
MAX_QUEUE_SIZE=20
CPU_TIME_LIMIT=3
MAX_CPU_TIME_LIMIT=5
WALL_TIME_LIMIT=5
MAX_WALL_TIME_LIMIT=8

ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true

MEMORY_LIMIT=2048000
MAX_MEMORY_LIMIT=2048000
