const sanitizeFileName = (value = '') => String(value)
  .replace(/[\\/:*?"<>|]/g, '-')
  .replace(/\s+/g, ' ')
  .trim() || 'tailored-resume';

const texEscapes = {
  '\\': '\\textbackslash{}',
  '&': '\\&',
  '%': '\\%',
  '$': '\\$',
  '#': '\\#',
  '_': '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
};

const escapeTex = (value = '') => String(value)
  .replace(/[\\&%$#_{}~^]/g, (character) => texEscapes[character])
  .replace(/\r?\n/g, ' ')
  .replace(/\s+/g, ' ')
  .trim();

const itemText = (item) => escapeTex(item?.text || item || '');

const renderItems = (items = []) => {
  const validItems = items.map(itemText).filter(Boolean);
  if (!validItems.length) return '';
  return `\\begin{ResumeItems}\n${validItems.map((item) => `  \\item ${item}`).join('\n')}\n\\end{ResumeItems}`;
};

const downloadBlob = (blob, fileName) => {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
};

const loadAvatarAsset = async (avatarUrl) => {
  if (!avatarUrl) return null;
  try {
    const response = await fetch(avatarUrl);
    if (!response.ok) return null;
    const blob = await response.blob();
    const extension = { 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp' }[blob.type] || 'png';
    return { blob, fileName: `resume-avatar.${extension}` };
  } catch {
    return null;
  }
};

export const downloadResumeTex = async ({ resume, user, job }) => {
  const content = resume?.content || {};
  const sections = Array.isArray(content.sections) ? content.sections : [];
  const skills = Array.isArray(content.skills) ? content.skills : [];
  const name = escapeTex(user?.full_name?.trim() || '未填写姓名');
  const contact = [user?.phone, user?.email].filter(Boolean).map(escapeTex).join('\\quad ');
  const headline = escapeTex(content.headline || job?.title || resume?.title || '求职简历');
  const summary = escapeTex(content.summary || '');
  const avatarAsset = await loadAvatarAsset(user?.avatar_url);
  const renderedSections = sections
    .filter((section) => section?.heading && Array.isArray(section?.items) && section.items.length)
    .map((section) => `\\ResumeSection{${escapeTex(section.heading)}}\n${renderItems(section.items)}`);

  if (skills.length) {
    renderedSections.push(`\\ResumeSection{专业技能}\n${renderItems(skills)}`);
  }
  if (!renderedSections.length && summary) {
    renderedSections.push(`\\ResumeSection{个人概述}\n${summary}`);
  }

  const header = avatarAsset
    ? `\\noindent\\begin{minipage}[c]{0.74\\textwidth}
\\centering
{\\fontsize{24pt}{24pt}\\selectfont\\bfseries ${name}}\\par
\\vspace{2.5mm}
${contact ? `${contact}\\par` : ''}
\\vspace{2.5mm}
${headline}\\par
\\end{minipage}\\hfill
\\begin{minipage}[c]{0.23\\textwidth}
\\raggedleft\\includegraphics[width=24mm,height=30mm,keepaspectratio]{${avatarAsset.fileName}}
\\end{minipage}`
    : `\\begin{center}
{\\fontsize{24pt}{24pt}\\selectfont\\bfseries ${name}}\\par
\\vspace{2.5mm}
${contact ? `${contact}\\par` : ''}
\\vspace{2.5mm}
${headline}\\par
\\end{center}`;

  const tex = `% !TeX program = xelatex
% Generated by Career Studio. Compile with XeLaTeX in Overleaf.
\\documentclass[UTF8,a4paper,10pt,fontset=none]{ctexart}
\\usepackage[left=9.52mm,right=9.64mm,top=7.93mm,bottom=8mm,headheight=0pt,headsep=0pt,footskip=0pt]{geometry}
\\usepackage{enumitem}
\\usepackage{fontspec}
\\usepackage{graphicx}
\\usepackage{xcolor}
\\definecolor{ResumeText}{HTML}{1A1A1A}
\\definecolor{ResumeRule}{HTML}{6B7280}
\\IfFontExistsTF{Arial}{\\setmainfont{Arial}\\setsansfont{Arial}}{\\setmainfont{TeX Gyre Heros}\\setsansfont{TeX Gyre Heros}}
\\IfFontExistsTF{Microsoft YaHei}{\\setCJKmainfont{Microsoft YaHei}[BoldFont={Microsoft YaHei Bold}]}{\\IfFontExistsTF{Noto Sans SC}{\\setCJKmainfont{Noto Sans SC}[AutoFakeBold=2.5]}{\\setCJKmainfont{FandolHei-Regular}[BoldFont={FandolHei-Bold}]}}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0pt}
\\renewcommand{\\familydefault}{\\sfdefault}
\\renewcommand{\\labelitemi}{\\textbullet}
\\newcommand{\\ResumeSection}[1]{\\par\\vspace{2.8mm}{\\fontsize{12pt}{14.5pt}\\selectfont\\bfseries #1\\par}\\vspace{1.55mm}{\\color{ResumeRule}\\hrule height 1.5pt}\\vspace{3.35mm}}
\\newenvironment{ResumeItems}{\\begin{itemize}[leftmargin=5.29mm,labelwidth=1.4mm,labelsep=1.75mm,itemindent=0pt,topsep=0pt,partopsep=0pt,parsep=0pt,itemsep=3pt]}{\\end{itemize}}
\\begin{document}
\\sffamily\\fontsize{10.5pt}{15.73pt}\\selectfont\\color{ResumeText}
${header}
${summary ? `\\ResumeSection{个人概述}\n${summary}\n` : ''}
${renderedSections.join('\n\\vspace{2pt}\n')}
\\end{document}
`;

  downloadBlob(new Blob([tex], { type: 'application/x-tex;charset=utf-8' }), `${sanitizeFileName(resume?.title)}.tex`);
  if (avatarAsset) downloadBlob(avatarAsset.blob, avatarAsset.fileName);
};
